### PR TITLE
Feature/get denormalized weight #26

### PR DESCRIPTION
**Pull request by travisdmathis**
##### Checklist

- [X] Linter status: 100% pass
- [X] Changes don't break existing behavior
- [X] Test coverage hasn't decreased

##### Testing

I have written tests to satisfy the additions to the pBasicSmartPool contract.

##### Refers/Fixes

Refers #26 

Total Hours: 4

### CODE REVIEW

**Comment by Alexintosh** [comment]
Feels like a separate PR business.

**Comment by travisdmathis** [comment]
> 
> 
> I agree that we should better format the code and apply linting more properly.
> 
> However I'm not fully agreeing with formatting which is applied now and also think this PR should not be the place for changing the formatting of 44 files.
> 
> @dmvt Any thoughts?

The formatting applied is coming from your prettier config in the project repo, it is not something I created.  This was formatted using that config.

**Comment by travisdmathis** [comment]
@dmvt requesting 1397.6 DOUGH for 4HRS total.

**Comment by dmvt** [comment]
@MickdeGraaf It's not a release yet because we're not deploying it. The release branch and ultimate stage would be between development and master.

Congrats on the first bounty @travisdmathis!!

**Comment by Alexintosh** [comment]
Good job @travisdmathis 🔥

**Pull request merged**
